import type { Metadata } from "next";
import "./styles/globals.css";
import 'lenis/dist/lenis.css'


export const metadata: Metadata = {
  title: "A25 Studio",
  description: "Generated by 20Studio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
